[application]

# App (Project) Name
name = "app"

# Dioxus App Default Platform
# desktop, web

default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "CV Manager"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "dist"]

# uncomment line below if using Router
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/output.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
